GET  http://localhost:5002/auth/google

###

//heroku server
GET https://cryptic-inlet-39368.herokuapp.com/

###

//heroku server
GET https://cryptic-inlet-39368.herokuapp.com/toto

###

GET  http://localhost:5002/api/current_user

###

GET  http://localhost:5002/api/logout